### ISSUE TITLE
What does Securify need the solc compiler for?

### ISSUE THREAD

**Issue by lukwue** [eth-sri/securify2#16]

**Comment by YannisSach** [comment]
Hi Luke,
Securify needs solc to get the AST which corresponds to the solidity file under analysis. This way we do not have to implement a parser. You could get a taste of how this AST looks like (even though it is not exactly the same as the one Securify uses) by executing `solc <solidity_contract> --ast-json`. You might want to take a look at `securify/solidity/solidity_ast_compiler.py` for a deeper insight.

Yannis

**Comment by lukwue** [comment]
Thanks!
