### ISSUE TITLE
Does the docker version of securify2 only support the analysis of contracts developed with solidity 0.5.12

### ISSUE THREAD

**Issue by xf97** [eth-sri/securify2#20]
I see this statement 
```
ARG SOLC=0.5.12
```
in Dockerflie

**Comment by xf97** [comment]
I have multiple versions of solc installed locally. Can I use securify2 to analyze bytecode directly?

**Comment by six-days** [comment]
you can use --solidity

**Comment by six-days** [comment]
> I have multiple versions of solc installed locally. Can I use securify2 to analyze bytecode directly?

you can use --solidity choose solc version

**Comment by xf97** [comment]
ok, i will try and thanks.
